# 005G: the technology matrix as data (one source for technology-matrix.json). Every value is either measured in this
# stage (see the artifact named in `evidence`) or read from the source listed in sources.md; UNVERIFIED says so.
import json, sys

CRITERIA = ["version", "codeLicense", "weightsLicense", "trainingData", "commercialUse", "offline", "node18", "androidArm64",
            "browserSafe", "determinism", "size", "apkDelta", "ramDelta", "coldStart", "latency", "buildComplexity",
            "nativeToolchain", "maintenance", "supplyChainRisk", "pinHash", "topKConfidence", "nonCircularCompatible",
            "sameModelCiAndPhone", "pythonInProduction", "cloudOrKeys", "duplicatesBuildPlanSubsystem"]

def t(id, family, verdict, why, placement, evidence, **c):
    missing = [k for k in CRITERIA if k not in c]
    if missing: raise SystemExit(f"{id}: missing {missing}")
    return {"id": id, "family": family, "verdict": verdict, "why": why, "placement": placement, "evidence": evidence, "criteria": {k: c[k] for k in CRITERIA}}

NA = "n/a"
paddle_common = dict(codeLicense="Apache-2.0 (PaddleOCR)", weightsLicense="Apache-2.0 (HF cardData, verified)", trainingData="not disclosed per dataset (PaddleOCR 3.0 / PP-OCRv5 / PP-OCRv6 reports: auto-labelled, parsed PDFs/e-books, synthesis) — UNVERIFIED for non-commercial components", commercialUse="yes by licence; data-provenance residual risk named", offline="yes (local file, SHA-256 checked; no run-time download in our harness)", browserSafe="yes (ONNX via onnxruntime-web)", nativeToolchain="none (WASM route)", pythonInProduction="no", cloudOrKeys="none", nonCircularCompatible="yes: image-only candidate per crop, sees no scale/span/chain", topKConfidence="yes: CTC digit-constrained prefix beam top-K with posteriors; greedy mean char prob", duplicatesBuildPlanSubsystem="overlaps the lattice's glyph classifier (ocr.ts templates) — intended: an independent witness, not a duplicate pipeline")

T = []
T.append(t("paddleocr-ppocrv6-tiny-rec", "OCR", "ADOPT_NEXT", "103/103 real exact, 0 confident-wrong on real, 4/707 confident-wrong on 775; 4.46 MB; 44 ms/label on WASM Node 18; bit-identical Node 18 vs 22.", "source-metrics recogniser interface + new package numeric-recogniser-ort (integration-map.md)", ["ocr-bakeoff.json", "ocr-bakeoff.md", "deployment-matrix.md"],
  version="HF PaddlePaddle/PP-OCRv6_tiny_rec_onnx @2612ab37, inference.onnx sha256 9ef676d6…", size="4 462 639 B (4.11 MB deflated)", apkDelta="+4.11 MB (model) + 3.7 MB runtime (shared, route A)", ramDelta="+160–200 MiB RSS with the runtime (process-lifetime WASM instance)", coldStart="522 ms (WASM, Node 18, x86-64)", latency="44 ms mean / 61 ms p95 per label (WASM Node 18); 14.5 ms native", node18="yes (measured)", androidArm64="expected via the same WASM in nodejs-mobile 18.20.4; NOT run on a device here", determinism="WASM Node 18 ≡ Node 22 bit-identical 775/775; native vs WASM Δp ≤ 3.1e-5", buildComplexity="low: two assets + one npm dependency", maintenance="active (released 2026-06)", supplyChainRisk="low: pinned file + hash, no install script, no network", pinHash="yes", sameModelCiAndPhone="yes (route A)", **paddle_common))
T.append(t("paddleocr-en-ppocrv5-mobile-rec", "OCR", "PILOT", "Second-best real accuracy (101/103, 0 confident-wrong); the alternative model if v6 tiny misses the next blind protocol, or the second model of P3 (two-model agreement).", "same seam as v6 tiny; behind a model id in the recogniser manifest", ["ocr-bakeoff.json"],
  version="HF PaddlePaddle/en_PP-OCRv5_mobile_rec_onnx @3fafbc3b, sha256 b5f833df…", size="7 848 423 B (7.23 MB deflated)", apkDelta="+7.23 MB", ramDelta="+180–220 MiB RSS", coldStart="661 ms (WASM Node 18)", latency="126 ms mean (WASM Node 18); 42 ms native", node18="yes (measured)", androidArm64="as v6 tiny; not run on device", determinism="WASM Node 18 ≡ Node 22 bit-identical", buildComplexity="low", maintenance="active", supplyChainRisk="low", pinHash="yes", sameModelCiAndPhone="yes (route A)", **paddle_common))
T.append(t("paddleocr-latin-ppocrv5-mobile-rec", "OCR", "DEFER", "No advantage over en/v6 tiny on digits (102/103, 1 confident-wrong on real: '20' p 0.986 on a half-hidden 120); its model card is copy-pasted.", "none", ["ocr-bakeoff.json"],
  version="HF latin_PP-OCRv5_mobile_rec_onnx @89d3a50e, sha256 7888113…", size="8 042 023 B", apkDelta="+7.3 MB", ramDelta="≈ en v5", coldStart="762 ms (WASM Node 18)", latency="127 ms (WASM Node 18)", node18="yes", androidArm64="as above", determinism="as above", buildComplexity="low", maintenance="active", supplyChainRisk="low; card metadata unreliable", pinHash="yes", sameModelCiAndPhone="yes", **paddle_common))
T.append(t("paddleocr-ppocrv5-mobile-rec-multilingual", "OCR", "DEFER", "Same accuracy class as en v5 at twice the size (16.5 MB).", "none", ["ocr-bakeoff.json"],
  version="HF PP-OCRv5_mobile_rec_onnx @ed152b8b, sha256 da72dc72…", size="16 534 782 B", apkDelta="+14.1 MB", ramDelta="+240 MiB (native run)", coldStart="225 ms native", latency="52 ms native (contended)", node18="expected (not run on WASM)", androidArm64="as above", determinism="not separately measured", buildComplexity="low", maintenance="active", supplyChainRisk="low", pinHash="yes", sameModelCiAndPhone="yes", **paddle_common))
T.append(t("paddleocr-ppocrv6-small-rec", "OCR", "DEFER", "Best accuracy among phone-sized models (769/775) but 21 MB and 189 ms/label on WASM; revisit only if tiny fails a blind protocol on legibility.", "none (candidate upgrade of the same seam)", ["ocr-bakeoff.json"],
  version="HF PP-OCRv6_small_rec_onnx @b8f84f0b, sha256 5435fd74…", size="21 159 378 B (18.5 MB deflated)", apkDelta="+18.5 MB", ramDelta="+250 MiB", coldStart="542 ms WASM", latency="189 ms WASM Node 18", node18="yes", androidArm64="as above", determinism="WASM Node 18 ≡ Node 22 bit-identical", buildComplexity="low", maintenance="active", supplyChainRisk="low", pinHash="yes", sameModelCiAndPhone="yes", **paddle_common))
T.append(t("paddleocr-ppocrv6-medium-rec", "OCR", "RESEARCH_ONLY", "Quality ceiling (769/775) at 76.6 MB; a research oracle for future label truth, never a phone asset.", "research harness only", ["ocr-bakeoff.json"],
  version="HF PP-OCRv6_medium_rec_onnx @50c7eaca, sha256 9c09abf0…", size="76 554 979 B", apkDelta="+66.9 MB (rejected)", ramDelta="+350 MiB", coldStart="392 ms native", latency="148 ms native", node18="expected", androidArm64="impractical", determinism="not measured on WASM", buildComplexity="low", maintenance="active", supplyChainRisk="low", pinHash="yes", sameModelCiAndPhone="impractical", **paddle_common))
T.append(t("onnxruntime-web", "RUNTIME", "ADOPT_NEXT", "Runs the pinned model inside the existing Node-18 analyzer bundle on CI and phone: 0 new .so, ABI-independent 3.7 MB, no telemetry, bit-identical Node 18/22.", "packages/numeric-recogniser-ort (new); apps/local-analyzer assets", ["deployment-matrix.md", "ocr-bakeoff.json"],
  version="1.30.0 (npm)", codeLicense="MIT", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes (wasmPaths local; no fetch)", node18="yes (measured, incl. no-ICU shim)", androidArm64="expected (libnode has WASM tiers, no --jitless); NOT run on a device", browserSafe="yes", determinism="bit-identical outputs Node 18/22 x86-64; no relaxed-SIMD in the .wasm (compiles on V8 10.2)", size="ort-wasm-simd-threaded.wasm 14 239 897 B (3.67 MB deflated) + 78 KB bundled JS", apkDelta="≈ +3.7 MB once for all ABIs", ramDelta="+160–200 MiB RSS per process (WASM instance kept); mitigate with a worker thread", coldStart="0.35–0.66 s per session", latency="≈ 3× native", buildComplexity="low", nativeToolchain="none", maintenance="active (monthly releases)", supplyChainRisk="low: no install script; deps bundled; pin + hash the .wasm", pinHash="npm exact version + .wasm sha256 in manifest.json", topKConfidence="n/a (runtime)", nonCircularCompatible="n/a (runtime)", sameModelCiAndPhone="yes — the same .wasm and model bytes", pythonInProduction="no", cloudOrKeys="none (no telemetry strings in any .wasm)", duplicatesBuildPlanSubsystem="no"))
T.append(t("onnxruntime-node", "RUNTIME", "RESEARCH_ONLY", "Fast native benchmark runtime; no Android build, telemetry code in ≥ 1.29 native binaries, postinstall downloads CUDA on linux/x64 unless skipped; would break CI/phone parity.", "research harness only", ["deployment-matrix.md"],
  version="1.30.0", codeLicense="MIT", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes at run time; install script downloads CUDA EP (ONNXRUNTIME_NODE_INSTALL=skip)", node18="yes (N-API 6)", androidArm64="no prebuilt (os: win32/darwin/linux)", browserSafe="no", determinism="deterministic per machine; differs from WASM by ≤ 3.1e-5", size="288 MB package (all platforms); linux-x64 libonnxruntime 45.8 MB", apkDelta="n/a", ramDelta="+100–180 MiB", coldStart="63–180 ms", latency="14.5 ms/label (v6 tiny)", buildComplexity="high for Android (cross-build N-API addon)", nativeToolchain="yes", maintenance="active", supplyChainRisk="medium: install-time download; telemetry code (no connect observed in an 8 s strace)", pinHash="version only", topKConfidence=NA, nonCircularCompatible=NA, sameModelCiAndPhone="no", pythonInProduction="no", cloudOrKeys="telemetry endpoint compiled in (1DS)", duplicatesBuildPlanSubsystem="no"))
T.append(t("onnxruntime-android", "RUNTIME", "REJECT", "Second engine beside CI's (parity broken), +12.4 MB per ABI, and 1.29+ AARs add INTERNET/ACCESS_NETWORK_STATE and a TelemetryInitializer provider.", "nowhere in production", ["deployment-matrix.md"],
  version="1.30.0 AAR (and 1.28.0 compared)", codeLicense="MIT", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="telemetry on by default ≥ 1.29 (1.28.0: none)", node18="n/a", androidArm64="yes (JNI)", browserSafe="no", determinism="MLAS kernels differ by CPU", size="AAR 53 MB (4 ABIs); arm64 .so 32 990 480 B", apkDelta="+12.4 MB arm64 (deflated) per ABI", ramDelta="not measured", coldStart="not measured", latency="not measured", buildComplexity="high (JNI bridge + Kotlin↔Node protocol)", nativeToolchain="yes", maintenance="active", supplyChainRisk="telemetry provider + permissions", pinHash="Maven version", topKConfidence=NA, nonCircularCompatible=NA, sameModelCiAndPhone="no", pythonInProduction="no", cloudOrKeys="Microsoft 1DS telemetry", duplicatesBuildPlanSubsystem="would duplicate the Node pipeline's recogniser on the Kotlin side"))
T.append(t("rapidocr", "OCR", "RESEARCH_ONLY", "Reference implementation of PaddleOCR pre/post-processing: our Node harness matches it on 771/775 crops (4 borderline resize flips). Python and run-time model downloads exclude it from production.", "research harness only", ["ocr-bakeoff.json (rapidocrReference)"],
  version="rapidocr 3.9.2 (PyPI)", codeLicense="Apache-2.0", weightsLicense="Apache-2.0 (redistributed PaddleOCR)", trainingData="as PaddleOCR", commercialUse="yes", offline="no by default (downloads from ModelScope)", node18="n/a (Python)", androidArm64="no", browserSafe="no", determinism="cv2 fixed-point resize differs from a float resize on borderline crops", size="27 MB wheel", apkDelta=NA, ramDelta=NA, coldStart=NA, latency="35.9 ms/label (Python, 1 thread)", buildComplexity=NA, nativeToolchain="Python + cv2", maintenance="active", supplyChainRisk="run-time download", pinHash="version", topKConfidence="greedy + score", nonCircularCompatible="n/a", sameModelCiAndPhone="no", pythonInProduction="would be yes → rejected", cloudOrKeys="model download at run time", duplicatesBuildPlanSubsystem="no"))
T.append(t("tesseract", "OCR", "REJECT", "89.5 % exact, 28–52 confident misreads on 775; condensed 24/48, condensed italic 6/24; top-K only per symbol.", "nowhere", ["ocr-bakeoff.json"],
  version="tesseract.js 7.0.0 / core 7.0.0 (Tesseract 5 LSTM), eng best_int", codeLicense="Apache-2.0", weightsLicense="Apache-2.0 (tessdata_best)", trainingData="Google-trained; corpus not published (UNVERIFIED)", commercialUse="yes", offline="yes with a local langPath (default fetches jsDelivr)", node18="yes (measured)", androidArm64="same WASM possible", browserSafe="yes", determinism="Node 18 ≡ Node 22 775/775", size="core .wasm 2.86 MB + glue 3.9 MB + traineddata 2.95 MB", apkDelta="≈ +5.5 MB", ramDelta="≈ +110 MiB (RSS 63 → 174 MiB)", coldStart="443 ms", latency="20 ms/label (×3 upscale)", buildComplexity="low", nativeToolchain="none", maintenance="active", supplyChainRisk="CVEs via crafted traineddata; default CDN fetch", pinHash="version + traineddata hash", topKConfidence="per-symbol choices only", nonCircularCompatible="yes", sameModelCiAndPhone="yes", pythonInProduction="no", cloudOrKeys="CDN by default", duplicatesBuildPlanSubsystem="overlaps the template reader"))
T.append(t("google-mlkit-text-recognition", "OCR", "REJECT", "Proprietary, sends usage metrics to Google, Android-only so CI cannot run the same engine; comparison-only by brief and not run (no device).", "nowhere", ["deployment-matrix.md", "licensing-matrix.md"],
  version="com.google.mlkit:text-recognition 16.0.1 (bundled-common 17.0.0)", codeLicense="proprietary (ML Kit Terms)", weightsLicense="proprietary", trainingData="proprietary", commercialUse="allowed under Google terms; not open source", offline="inference on device; metrics to Google", node18="no", androidArm64="yes", browserSafe="no", determinism="unknown", size="arm64 .so 11 064 544 B + assets 1.49 MB", apkDelta="≈ +5.5 MB per ABI + Play-services deps", ramDelta="not measured", coldStart="not measured", latency="not measured", buildComplexity="medium (Kotlin bridge)", nativeToolchain="AAR", maintenance="no release since 2024-08", supplyChainRisk="closed binary", pinHash="Maven version", topKConfidence="per-element confidence", nonCircularCompatible="yes as a candidate", sameModelCiAndPhone="no", pythonInProduction="no", cloudOrKeys="usage metrics", duplicatesBuildPlanSubsystem="would add a second, Android-only reader"))
T.append(t("pdfjs-dist", "PDF", "PILOT", "Reads text with positions, operators and vector paths on Node 18 and no-ICU; Aster's scale stated (1:500) and measured from its scale bar agree to 3e-5; walls exact as a 40-vertex polygon. The integration stage after the recogniser.", "source-package document facts + a document observation extractor (integration-map.md)", ["pdf-vector-probe.json", "pdf-vector-probe.md"],
  version="4.8.69 (last Node ≥ 18 line); latest 6.4.299 needs Node ≥ 22.13", codeLicense="Apache-2.0", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="yes (measured, bundled, no-ICU)", androidArm64="same bundle (pure JS)", browserSafe="yes", determinism="identical outputs Node 18 vs 22 on 3 PDFs", size="bundle 3 081 099 B (0.65 MB deflated)", apkDelta="+0.65 MB", ramDelta="process RSS 96–110 MiB after parsing a 1-page outline PDF (Node 18/22)", coldStart="45–55 ms import (unbundled)", latency="371–388 ms per 1-page outline PDF incl. text + operator list (Node 18)", buildComplexity="low (worker in-thread)", nativeToolchain="none (omit optional canvas/path2d)", maintenance="active (monthly) — but the Node-18 line gets no fixes", supplyChainRisk="medium: old line pinned; CVE-2024-4367 fixed; parse untrusted PDFs with isEvalSupported:false, no scripting/rendering", pinHash="npm exact + lockfile integrity", topKConfidence="n/a (exact text)", nonCircularCompatible="yes: stated scale and bar are independent document witnesses", sameModelCiAndPhone="yes", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="no (nothing parses PDFs today)"))
T.append(t("apache-pdfbox", "PDF", "RESEARCH_ONLY", "Independent oracle: identical text positions to 0.01 pt; JVM-only so it would be a second pipeline in production.", "test oracle only", ["pdf-vector-probe.json (pdfbox)"],
  version="3.0.8", codeLicense="Apache-2.0", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="no (JVM)", androidArm64="only via PdfBox-Android", browserSafe="no", determinism="deterministic", size="pdfbox-app 13.6 MB", apkDelta=NA, ramDelta=NA, coldStart="JVM", latency="240–518 ms per file (incl. JVM start)", buildComplexity="n/a", nativeToolchain="JVM", maintenance="active", supplyChainRisk="low", pinHash="Maven", topKConfidence=NA, nonCircularCompatible="yes", sameModelCiAndPhone="no", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="would duplicate PDF.js"))
T.append(t("pdfbox-android", "PDF", "REJECT", "Android-only second PDF pipeline, stale since 2023 (10 patch releases behind).", "nowhere", ["licensing-matrix.md"],
  version="com.tom-roush:pdfbox-android 2.0.27.0", codeLicense="Apache-2.0", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="no", androidArm64="yes", browserSafe="no", determinism="n/a", size="not measured (Maven Central rate-limited the download)", apkDelta="not measured", ramDelta=NA, coldStart=NA, latency=NA, buildComplexity="medium", nativeToolchain="no", maintenance="stale (2023)", supplyChainRisk="unmaintained", pinHash="Maven", topKConfidence=NA, nonCircularCompatible="yes", sameModelCiAndPhone="no", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="duplicates PDF.js"))
T.append(t("pdfium", "PDF", "DEFER", "PDF.js lacked no capability these documents need; PDFium adds per-ABI binaries or a WASM build with licence-hygiene issues and a continuous CVE stream.", "none", ["pdf-vector-probe.md"],
  version="chromium/8076 (bblanchon binaries); @hyzyla/pdfium 2.1.13", codeLicense="BSD-3-Clause + Apache-2.0", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="WASM build plausible (not run)", androidArm64="native binaries exist", browserSafe="WASM", determinism="not measured", size="≈ 4 MB WASM", apkDelta="≈ +2 MB (WASM) or per-ABI .so", ramDelta=NA, coldStart=NA, latency=NA, buildComplexity="medium", nativeToolchain="optional", maintenance="active", supplyChainRisk="high CVE cadence; npm wrapper ships wrong licence file", pinHash="possible", topKConfidence=NA, nonCircularCompatible="yes", sameModelCiAndPhone="possible via WASM", pythonInProduction="no", cloudOrKeys="index.esm.cdn entry fetches jsDelivr", duplicatesBuildPlanSubsystem="duplicates PDF.js"))
T.append(t("dwg-dxf-readers", "PDF", "DEFER", "Not built (brief). LibreDWG is GPL-3.0 (reject); ODA commercial; DXF: dxf-parser 1.1.2 (MIT) / ezdxf 1.4.4 (MIT) exist. Aster and Galaktyka publish DWG outlines (hashed).", "none", ["pdf-vector-probe.md"],
  version="survey only", codeLicense="LibreDWG GPL-3.0; dxf-parser MIT; ezdxf MIT; ODA commercial", weightsLicense=NA, trainingData=NA, commercialUse="DXF MIT options yes; DWG needs commercial SDK", offline="yes", node18="dxf-parser JS", androidArm64="JS", browserSafe="dxf-parser yes", determinism="n/a", size=NA, apkDelta=NA, ramDelta=NA, coldStart=NA, latency=NA, buildComplexity="high for DWG", nativeToolchain="DWG: yes", maintenance="varies", supplyChainRisk="n/a", pinHash="possible", topKConfidence=NA, nonCircularCompatible="yes", sameModelCiAndPhone="DXF: yes", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="no"))
T.append(t("opencv-android", "CV", "REJECT", "Bit-identical to source-cv on components/morphology; +9.8 MB per ABI; a JNI path the Node analyzer cannot call (second CV implementation).", "nowhere", ["cv-probe.md"],
  version="org.opencv:opencv 4.14.0", codeLicense="Apache-2.0", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="no", androidArm64="yes", browserSafe="no", determinism="deterministic (HoughLinesP fixed RNG)", size="AAR 123 MB; arm64 libopencv_java4.so 24 657 160 B", apkDelta="+9.77 MB per ABI", ramDelta=NA, coldStart=NA, latency="Hough ~12× faster than source-cv Hough", buildComplexity="medium", nativeToolchain="yes", maintenance="active", supplyChainRisk="CVE-2025-53644 class (image decoders)", pinHash="Maven", topKConfidence=NA, nonCircularCompatible=NA, sameModelCiAndPhone="no", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="duplicates source-cv"))
T.append(t("opencv-js", "CV", "DEFER", "Same results as source-cv where comparable; no LSD in the WASM build; 3.8 MB for capabilities BuildPlan has; no current failure is a CV-primitive failure.", "none", ["cv-probe.md", "cv-probe.json"],
  version="@techstark/opencv-js 5.0.0-release.1 (OpenCV 5.0.0)", codeLicense="Apache-2.0", weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="expected (WASM)", androidArm64="same WASM", browserSafe="yes", determinism="deterministic", size="13.3 MB (3.76 MB deflated)", apkDelta="+3.8 MB", ramDelta="not measured", coldStart="not measured", latency="components 2.3 ms, erode 1.4 ms, HoughP 21.5 ms per sheet", buildComplexity="low", nativeToolchain="none", maintenance="community wrapper, active", supplyChainRisk="large opaque bundle", pinHash="npm", topKConfidence=NA, nonCircularCompatible=NA, sameModelCiAndPhone="yes", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="duplicates source-cv"))
for fid, verdict, why, ver, code, w, data in [
  ("roomformer", "REJECT", "Point-cloud density input (wrong modality); Structured3D/SceneCAD non-commercial.", "ywyue/RoomFormer (2023-08)", "MIT", "unstated", "Structured3D (non-commercial), SceneCAD/ScanNet (non-commercial)"),
  ("polyroom-fri-net-slibo-net", "REJECT", "Point-cloud input; no licence (PolyRoom) or unverified; Structured3D.", "3dv-casia/PolyRoom (2025-05)", "none (all rights reserved)", "unstated", "Structured3D, SceneCAD"),
  ("deepfloorplan-family", "REJECT", "GPL-3.0 code, no weight grant, LIFULL/R2V research-only data.", "zlzeng/DeepFloorplan (2021), zcemycl/TF2DeepFloorplan (2023)", "GPL-3.0", "unstated", "R2V/LIFULL (universities, not-for-profit), R3D (no licence)"),
  ("cubicasa5k", "RESEARCH_ONLY", "Dataset and repo non-commercial (CC BY-NC vs BY-NC-SA inconsistent).", "CubiCasa/CubiCasa5k (2019)", "CC BY-NC 4.0", "unstated → repo licence", "CubiCasa5K CC BY-NC(-SA) 4.0"),
  ("raster-to-vector", "REJECT", "LIFULL data research-only; Torch7.", "art-programmer/FloorplanTransformation (2019)", "MIT", "unstated", "LIFULL (permission, research only)"),
  ("raster-to-graph", "REJECT", "GPL-3.0; LIFULL + terms-of-use annotations.", "HSZVIS/Raster-to-Graph (2026-05)", "GPL-3.0", "unstated", "LIFULL high-res + own annotations (terms)"),
  ("raster2seq", "RESEARCH_ONLY", "Strongest raster→polygon model; every checkpoint trained on non-commercial/research data.", "Cornell-VAILab/Raster2Seq (2026-06)", "MIT", "MIT tag (does not override data terms)", "Structured3D, CubiCasa5K, Raster2Graph/LIFULL"),
  ("ultralytics-yolo-floorplan", "REJECT", "AGPL-3.0 code and every trained model; Enterprise licence needed for closed source.", "Ultralytics YOLOv8/11 + Roboflow Universe datasets", "AGPL-3.0", "AGPL-3.0", "uploader-declared CC BY 4.0, provenance unknown (UNVERIFIED)"),
  ("rmbg-wall-segmentation", "REJECT", "Base model RMBG-1.4 non-commercial; CubiCasa data.", "phungpx/RMBG-1.4-wall-segmentation-cubicassa (2026-06)", "other", "BRIA RMBG-1.4 non-commercial", "CubiCasa5K"),
  ("rf-detr-2dplan2strct", "REJECT", "Checkpoint explicitly non-commercial research only.", "OsamaMo/2dplan2strct (2026-09)", "Apache-2.0 (RF-DETR)", "non-commercial research only", "not stated"),
  ("fpvec-lab", "DEFER", "Nothing released yet; ResPlan-based data CC BY 4.0 — watch.", "Cyprinus12138/fpvec-lab (2026-08)", "announced MIT", "none released", "ResPlan-FP CC BY 4.0 / corrected CubiCasa NC-SA"),
  ("mlstructfp", "RESEARCH_ONLY", "MIT code; weights unstated; data licence unverified.", "MLSTRUCT/MLStructFP (2026-04)", "MIT", "unstated", "954 plans behind a form (UNVERIFIED)"),
]:
    T.append(t(fid, "FLOORPLAN_ML", verdict, why, "would be a source-vision (VisionReasoner PLAN task) observation provider — never a resolver", ["floorplan-ml-audit.md"],
      version=ver, codeLicense=code, weightsLicense=w, trainingData=data, commercialUse="no", offline="possible", node18="not tested (no integration)", androidArm64="not tested", browserSafe="via ONNX/WASM only where exportable", determinism="not measured", size="see floorplan-ml-audit.md", apkDelta="not measured", ramDelta="not measured", coldStart="not measured", latency="not measured", buildComplexity="high (custom ops / Python post-processing typical)", nativeToolchain="typically", maintenance=ver.split("(")[-1].rstrip(")"), supplyChainRisk="licence (weights/data)", pinHash="possible", topKConfidence="per-element scores", nonCircularCompatible="only as observations", sameModelCiAndPhone="not evaluated", pythonInProduction="post-processing often Python", cloudOrKeys="none", duplicatesBuildPlanSubsystem="overlaps wall bands / envelope as a witness"))
geom = dict(weightsLicense=NA, trainingData=NA, commercialUse="yes", offline="yes", node18="yes (identical results Node 18 = Node 22)", androidArm64="same JS", browserSafe="yes", apkDelta="< 0.1 MB", ramDelta="negligible", coldStart="negligible", nativeToolchain="none", pythonInProduction="no", cloudOrKeys="none", topKConfidence=NA, nonCircularCompatible="yes (low-level geometry only)", sameModelCiAndPhone="yes")
T.append(t("polygon-clipping", "GEOMETRY", "REJECT", "Stale; reproduced 'Unable to complete output ring' on 12 rotated walls.", "nowhere", ["geometry-library-audit.md", "geometry-library-probe.json"], version="0.15.7", codeLicense="MIT", determinism="34/35 cases (1 throws)", size="55 KB", latency="0.55 ms median", buildComplexity="low", maintenance="stale (2024-04)", supplyChainRisk="known robustness bugs", pinHash="npm", duplicatesBuildPlanSubsystem="model/geometry vector primitives", **geom))
T.append(t("polyclip-ts", "GEOMETRY", "DEFER", "Correct and order-invariant on all 35 cases; but nothing in a current failure needs a vector boolean.", "first choice if room polygons / tracePolygon need a union", ["geometry-library-audit.md"], version="0.16.8", codeLicense="MIT (LICENSE omits upstream notices, issue #27)", determinism="35/35 order-invariant; identical Node 18/22", size="40 KB", latency="3.2 ms median", buildComplexity="low", maintenance="maintained fork (Turf 7)", supplyChainRisk="low", pinHash="npm", duplicatesBuildPlanSubsystem="model/geometry vector primitives", **geom))
T.append(t("clipper2", "GEOMETRY", "DEFER", "Integer-robust with offsets; JS ports stale or prerelease; 1 µm quantisation; vertex set depends on input order in 10/35 cases; open-path delta trap.", "none now", ["geometry-library-audit.md"], version="Clipper2 2.0.1 (C++); clipper2-js 1.2.4; clipper2-ts 2.0.1-18", codeLicense="BSL-1.0", determinism="area order-invariant; vertex set not (10/35)", size="1.9 MB package", latency="0.8 ms median", buildComplexity="low", maintenance="core active; JS ports stale/prerelease", supplyChainRisk="port quality; clipper2-js 1.2.4 peer-depends on @angular/core+common ^15 (npm installs them; npm audit: high advisories, no fix) — prefer clipper2-ts (no deps)", pinHash="npm", duplicatesBuildPlanSubsystem="model/geometry vector primitives", **geom))
T.append(t("jts-jsts", "GEOMETRY", "RESEARCH_ONLY", "The oracle: exact and order-invariant; a test-only dev dependency candidate for verification oracles.", "packages/verification tests only (if adopted)", ["geometry-library-audit.md"], version="JTS 1.20.0 / JSTS 2.12.1", codeLicense="JTS EPL-2.0|EDL-1.0; JSTS EDL-1.0|EPL-1.0", determinism="35/35", size="7 MB package", latency="3.9 ms median", buildComplexity="low", maintenance="JTS active; JSTS 2024-11", supplyChainRisk="low", pinHash="npm", duplicatesBuildPlanSubsystem="no (oracle)", **geom))
for gid, verdict, why, ver, code in [
  ("manifold-3d", "DEFER", "Apache-2.0, 541 KB WASM mesh booleans/manifold checks; no current defect in the 3D compiler — a candidate oracle for geometryClosureAudit only.", "3.5.4", "Apache-2.0"),
  ("cgal", "REJECT", "GPL/LGPL or commercial licence.", "6.2.1", "GPL-3.0+/LGPL-3.0+ or commercial"),
  ("open-cascade", "REJECT", "LGPL-2.1+exception, heavy native B-rep kernel; no need.", "8.0.1", "LGPL-2.1 + OCCT exception"),
]:
    T.append(t(gid, "GEOMETRY_3D", verdict, why, "none", ["STAGE report §3D"], version=ver, codeLicense=code, weightsLicense=NA, trainingData=NA, commercialUse="yes" if gid == "manifold-3d" else "licence-dependent", offline="yes", node18="manifold WASM plausible (not run)" if gid == "manifold-3d" else "no", androidArm64="WASM" if gid == "manifold-3d" else "native", browserSafe="WASM" if gid == "manifold-3d" else "no", determinism="not measured", size="541 KB wasm" if gid == "manifold-3d" else "large", apkDelta="not measured", ramDelta="not measured", coldStart="not measured", latency="not measured", buildComplexity="low" if gid == "manifold-3d" else "high", nativeToolchain="none" if gid == "manifold-3d" else "yes", maintenance="active", supplyChainRisk="low" if gid == "manifold-3d" else "licence", pinHash="npm" if gid == "manifold-3d" else "n/a", topKConfidence=NA, nonCircularCompatible=NA, sameModelCiAndPhone="possible" if gid == "manifold-3d" else "no", pythonInProduction="no", cloudOrKeys="none", duplicatesBuildPlanSubsystem="geometry compiler / closure audit"))

out = {"schema": "buildapp.analyzer-005g.technology-matrix", "version": "1.0.0", "criteria": CRITERIA,
       "verdicts": ["ADOPT_NEXT", "PILOT", "DEFER", "RESEARCH_ONLY", "REJECT"],
       "summary": {v: [x["id"] for x in T if x["verdict"] == v] for v in ["ADOPT_NEXT", "PILOT", "DEFER", "RESEARCH_ONLY", "REJECT"]},
       "keepCustom": ["source-metrics lattice (orientation passes, segmentation, glyph-count hypotheses, stability bracket) — as the second, independent witness", "source-metrics chains / dimension lines / non-circular metric solution", "source-cv (bit-identical to OpenCV where comparable)", "reconstruction envelope, bodies, decomposition, openings, resolver (semantic)", "geometry compiler tilers (watertight shared-vertex guarantee)", "source-package acquisition, security and document recording"],
       "technologies": T}
json.dump(out, open(sys.argv[1], "w"), indent=1, ensure_ascii=False)
print(len(T), {k: len(v) for k, v in out["summary"].items()})
