package com.buildplan.preview

import com.buildplan.preview.render.ArchitecturalPalette
import com.buildplan.preview.render.RenderStyle
import com.buildplan.preview.scene.BundleParser
import com.buildplan.preview.scene.BundleResult
import com.buildplan.preview.scene.GeometryPart
import com.buildplan.preview.scene.ModelScene
import com.buildplan.preview.scene.SemanticGroup
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * BUILDAPP-03G on the phone: the schema 1.6.0 parts and semantic groups —
 * roof planes, wall panels, platforms, exterior step runs, structural and
 * pergola members, unknown assemblies — parse and draw from the bundle alone.
 *
 * The bundles are the synthetic diversity fixtures' own, generated by
 * `npm run architecture:android-fixtures` into TEST resources (the APK ships
 * no fixture) and held current by packages/architecture/test. Nothing here
 * rebuilds geometry: every triangle is the compiler's.
 */
class ArchitecturalAssembliesTest {

    private val root: File = sequenceOf(
        File("src/test/resources/architecture"),
        File("app/src/test/resources/architecture"),
        File("apps/android/app/src/test/resources/architecture"),
    ).firstOrNull { it.isDirectory } ?: error("architecture fixture bundles not found from ${File(".").absolutePath}")

    private fun scene(name: String): ModelScene {
        val text = File(root, "$name.scene.json").readText()
        val bundle = when (val r = BundleParser.parse(text)) {
            is BundleResult.Ok -> r.bundle
            is BundleResult.Failure -> error("$name did not parse: ${r.message}")
        }
        return ModelScene.from(bundle, name, name, "")
    }

    private fun parts(s: ModelScene) = s.objects.flatMap { it.parts }

    @Test
    fun `the four fixture bundles parse, with every part known to this build`() {
        for (name in listOf("exterior-pergola", "exterior-entrance-canopy", "roof-dormer-gable", "unknown-feature")) {
            val s = scene(name)
            assertTrue("$name has geometry", s.objects.any { it.hasGeometry })
            for (p in parts(s)) {
                assertTrue("$name: part ${p.rawPart} is known", p.part != GeometryPart.OTHER)
                val raw = p.rawSemanticGroup
                if (raw != null) assertTrue("$name: group $raw is known", SemanticGroup.of(raw) != null)
            }
            for (o in s.objects) for (i in o.positions.indices) assertTrue("$name ${o.id}: finite", o.positions[i].isFinite())
        }
    }

    @Test
    fun `the new parts and groups arrive as themselves`() {
        val pergola = parts(scene("exterior-pergola"))
        assertTrue(pergola.any { it.part == GeometryPart.ROOF_PLANE && it.semanticGroup == SemanticGroup.ROOF_MAIN })
        assertTrue(pergola.any { it.semanticGroup == SemanticGroup.PERGOLA_MEMBER })
        val canopy = parts(scene("exterior-entrance-canopy"))
        assertTrue(canopy.any { it.part == GeometryPart.PLATFORM })
        assertTrue(canopy.any { it.part == GeometryPart.STEP_RUN && it.semanticGroup == SemanticGroup.STAIR })
        assertTrue(canopy.any { it.semanticGroup == SemanticGroup.STRUCTURAL_MEMBER })
        assertTrue(canopy.any { it.part == GeometryPart.ROOF_PLANE && it.semanticGroup == SemanticGroup.FLAT_ROOF })
        val dormer = parts(scene("roof-dormer-gable"))
        assertTrue(dormer.any { it.part == GeometryPart.WALL_PANEL && it.semanticGroup == SemanticGroup.WALL_MAIN })
        // a dormer's front wall is envelope, not a facade member
        assertTrue(dormer.none { it.semanticGroup == SemanticGroup.FACADE_FRAME })
    }

    @Test
    fun `an unknown assembly is drawn restrained and translucent, from what was observed only`() {
        val s = scene("unknown-feature")
        val unknown = s.objects.filter { o -> o.parts.any { it.part == GeometryPart.UNKNOWN_ASSEMBLY } }
        assertEquals(1, unknown.size)
        for (p in unknown.single().parts) {
            assertEquals(SemanticGroup.UNKNOWN_ASSEMBLY, p.semanticGroup)
            assertTrue(p.part.isTranslucent)
            val drawn = RenderStyle.ARCHITECTURAL.appearanceOf(p, p.materialId?.let { s.materials[it] }, s.styling)
            assertTrue("drawn translucent", drawn.isTranslucent && drawn.alpha < 1f)
            val a = ArchitecturalPalette.appearanceOf(p.semanticGroup, p.rawSemanticGroup, s.styling)
            assertTrue("restrained: a muted, partly transparent surface", (a.opacity ?: 1.0) < 1.0 && a.edge == "NONE")
            assertTrue("restrained: not brighter than a light render", (drawn.red + drawn.green + drawn.blue) / 3f <= 0.8f)
        }
    }
}
