#!/usr/bin/env python3
"""runtime_matrix.py - runtime-size-matrix.md for BUILDPLAN-ANALYZER-005M (RESEARCH ONLY).

    python -I -B research/analyzer-005m/runtime_matrix.py --manifest stage-reports/artifacts/analyzer-005m-vr2/model-manifest.json \
        --runs <W>/runs --libs <W>/llama.cpp/build/bin --quant <W>/manifests/quantised-sizes.json --out stage-reports/artifacts/analyzer-005m-vr2/runtime-size-matrix.md

Measured here: bytes of every GGUF that ran; peak anonymous RSS of the server per mode; median and p90 wall time per
mode; image tokens per mode; time to load (server log, weights already in RAM-backed tmpfs, i.e. warm); runtime library
bytes (this x86-64 build). From the publishers: BF16 checkpoint bytes and the official quantisations' bytes. Phones were
not available: no phone latency is claimed; published phone figures are quoted with their source in the prose.
"""
import argparse
import json
import os
import re

MODES = ['A_CROP_ONLY', 'B_FULL_PLAN', 'C_FULL_PLAN_MARKED_ROI', 'D_MARKED_ROI_PLUS_CROP', 'E_MARKED_ROI_PLUS_CROP_PLUS_OVERLAY']
RUNS = {'qwen3-vl-2b': ('Qwen/Qwen3-VL-2B-Instruct', 'qwen3-vl-2b'), 'qwen3-vl-4b': ('Qwen/Qwen3-VL-4B-Instruct', 'qwen3-vl-4b'),
        'internvl3.5-2b-instruct': ('OpenGVLab/InternVL3_5-2B-Instruct', 'internvl3.5-2b'), 'smolvlm2-2.2b': ('HuggingFaceTB/SmolVLM2-2.2B-Instruct', 'smolvlm2-2.2b')}
GB = 1e9
# Publisher figures, read 2026-10-07; quoted, never measured here (no phone in this container).
PHONES = [
    '## Phones: published figures only (nothing below was measured in 005M)', '',
    '| model / artifact | device, runtime | decode tok/s | prefill tok/s | time to first token | source |',
    '| --- | --- | --- | --- | --- | --- |',
    '| Qwen3-VL-2B, Q4_0 GGUF 1.39 GB, llama.cpp-based | Galaxy S25, CPU, 512-token context | 47.6 | 365 | 0.35–1.4 s | aihub.qualcomm.com/models/qwen3_vl_2b_instruct |',
    '| same | Galaxy S25, NPU | 36.1 | 2,356 | 55–219 ms | same |',
    '| Qwen3-VL-4B, w4a16 (QAIRT) | Galaxy S25, NPU | ≈ 15.5 | ≈ 1,300 | — ; vision encoder 149 ms (S25), 68.8 ms (S26), input size not stated | aihub.qualcomm.com/models/qwen3_vl_4b_instruct |',
    '| Gemma 3n E2B, int4 `.litertlm` | S24 Ultra, LiteRT-LM CPU / GPU | 16.1 / 15.6 | 110.5 / 816.4 | no published figure with an image | huggingface.co/google/gemma-3n-E2B-it-litert-lm |',
    '| SmolVLM2-2.2B / 500M | — | — | — | none published for phones; inference memory 4.9 GB (2.2B), 1.2 GB (500M) | arxiv.org/abs/2504.05299 |',
    '| InternVL3.5-2B | — | — | — | no phone report found | — |', '',
    'Arithmetic, not a measurement: a mode-D prompt for Qwen3-VL is a median 965 tokens (776 of them image tokens) and the '
    'reply 17 tokens (measured here). At the published S25 CPU rates that is ≈ 2.6 s of prefill + ≈ 0.4 s of decode, plus '
    'the vision encoder, which the figure does not include. Qualcomm quotes a 512-token context, shorter than one mode-D '
    'prompt, so this is an optimistic floor, not a phone latency.', '',
    '**Delivery limits** (Google Play, read 2026-10-07):',
    '- each asset or AI pack is at most 1.5 GB;',
    '- install-time content is at most 4 GB cumulative;',
    '- Play for On-device AI (beta) packs are likewise "up to 1.5GB".',
    '',
    'Source: support.google.com/googleplay/android-developer/answer/9859372, developer.android.com/google/play/on-device-ai.',
    'A pack above 1.5 GB has to be split across packs or downloaded outside Play.', '']


def size_class(b):
    return '≤ 1.0 GB' if b <= 1.0 * GB else ('1.0–2.0 GB' if b <= 2.0 * GB else ('2.0–4.0 GB' if b <= 4.0 * GB else '> 4.0 GB'))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--manifest', required=True)
    ap.add_argument('--runs', required=True)
    ap.add_argument('--libs', required=True)
    ap.add_argument('--quant', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    man = {m['id']: m for m in json.load(open(a.manifest))['models']}
    quant = json.load(open(a.quant))
    libs = {f: os.path.getsize(os.path.join(a.libs, f)) for f in os.listdir(a.libs)
            if re.match(r'lib(llama|ggml|ggml-base|ggml-cpu|mtmd)\.so\.\d', f) and not os.path.islink(os.path.join(a.libs, f))}
    lib_bytes = sum(libs.values())
    L = ['# 005M runtime and size matrix (generated by research/analyzer-005m/runtime_matrix.py)', '',
         'Container: 4 vCPU Xeon @ 2.8 GHz (AVX-512 + VNNI, no GPU), llama.cpp `988190680d5a` CPU build, 4 threads, 8k context. '
         '**Not a phone.** Latencies are this desktop CPU; RSS is the server process. Runtime libraries of this x86-64 build '
         f'(libllama + libggml* + libmtmd): **{lib_bytes / 1e6:.1f} MB**; the tokenizer travels inside the GGUF.', '',
         '## Bytes', '',
         '| model | BF16 checkpoint (publisher) | LLM Q8_0 (ran) | vision F16 (ran) | **pack as run** | LLM Q4_K_M | vision Q8_0 | **smallest pack (Q4_K_M + Q8_0 vision)** | class as run / smallest |',
         '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for label, (mid, _) in RUNS.items():
        m = man[mid]
        ran = m.get('ranGguf') or {}
        llm = next((v['bytes'] for k, v in ran.items() if not k.startswith('mmproj') and v.get('bytes')), None)
        vis = next((v['bytes'] for k, v in ran.items() if k.startswith('mmproj') and v.get('bytes')), None)
        bf16 = m['upstreamWeightBytes'] / (2 if 'SmolVLM2' in mid else 1)   # SmolVLM2-2.2B's safetensors are FP32
        q = quant.get(label, {})
        pack = (llm or 0) + (vis or 0) + lib_bytes
        small = (q.get('llmQ4_K_M') or 0) + (q.get('visionQ8_0') or 0) + lib_bytes
        L.append(f"| {label} | {bf16 / GB:.2f} GB{' (FP32 on the hub, halved)' if 'SmolVLM2' in mid else ''} | {llm / GB:.2f} GB | {vis / GB:.2f} GB | **{pack / GB:.2f} GB** | "
                 f"{q.get('llmQ4_K_M', 0) / GB:.2f} GB ({q.get('llmQ4_K_M_source', '')}) | {q.get('visionQ8_0', 0) / GB:.2f} GB ({q.get('visionQ8_0_source', '')}) | **{small / GB:.2f} GB** | {size_class(pack)} / {size_class(small)} |")
    L += ['', '## Time, memory and tokens (measured over every record of the model\'s largest matched run)', '',
          '| model | records | load (warm) | mode | median wall | p90 wall | median wall when the prompt cache missed | median image tokens | peak anon RSS |',
          '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for label, (mid, stem) in RUNS.items():
        path = os.path.join(a.runs, f'p2-{stem}.jsonl')
        if not os.path.exists(path) or sum(1 for _ in open(path)) < 835:
            path = os.path.join(a.runs, f'p1-{stem}.jsonl')
        recs = [json.loads(l) for l in open(path)]
        log = open(path.replace('.jsonl', '.server.log')).read() if os.path.exists(path.replace('.jsonl', '.server.log')) else ''
        mt = re.search(r'^(\d+)\.(\d+)\.(\d+)\.\d+ I srv\s+load_model: loaded multimodal model', log, re.M)
        load = f'{int(mt.group(1)) * 60 + int(mt.group(2)) + int(mt.group(3)) / 1000:.1f} s' if mt else '—'
        for mode in MODES:
            rs = [r for r in recs if r['mode'] == mode and 'wallMs' in r]
            w = sorted(r['wallMs'] for r in rs)
            cold = sorted(r['wallMs'] for r in rs if (r.get('cachedTokens') or 0) <= 16)
            tok = sorted(r.get('imageTokens') or 0 for r in rs)
            anon = max(((r.get('rss') or {}).get('RssAnon') or 0) for r in rs)
            L.append(f"| {label} | {len(recs)} | {load if mode == MODES[0] else ''} | {mode[0]} | {w[len(w) // 2] / 1000:.1f} s | {w[int(len(w) * 0.9)] / 1000:.1f} s | "
                     f"{(cold[len(cold) // 2] / 1000) if cold else float('nan'):.1f} s (n={len(cold)}) | {tok[len(tok) // 2]} | {anon / 1e9:.2f} GB |")
    L += ['', 'Peak RAM of a deployment ≈ the pack bytes (weights are memory-mapped and resident while answering) + the peak '
          'anonymous RSS above (KV cache, compute buffers, image tensors, the prompt cache capped at 2 GiB here).', '']
    L += PHONES
    open(a.out, 'w').write('\n'.join(L) + '\n')
    print(a.out)


if __name__ == '__main__':
    main()
