#!/usr/bin/env python3
"""summarize.py - markdown tables from the scorer's JSON (RESEARCH ONLY). Every number in the 005M report is read here.

    python -I -B research/analyzer-005m/summarize.py --dir stage-reports/artifacts/analyzer-005m-vr2 --out <dir>/bakeoff-tables.md
"""
import argparse
import json
import os

MODES = ['A_CROP_ONLY', 'B_FULL_PLAN', 'C_FULL_PLAN_MARKED_ROI', 'D_MARKED_ROI_PLUS_CROP', 'E_MARKED_ROI_PLUS_CROP_PLUS_OVERLAY']
SHORT = {m: m[0] for m in MODES}


def pct(r):
    if not r or r.get('rate') is None:
        return '—'
    lo, hi = r['wilson95']
    return f"{100 * r['rate']:.1f} % ({r['k']}/{r['n']}; {100 * lo:.0f}–{100 * hi:.0f})"


def short(r):
    if not r or r.get('rate') is None:
        return '—'
    return f"{100 * r['rate']:.0f} % ({r['k']}/{r['n']})"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    b = json.load(open(os.path.join(a.dir, 'matched-bakeoff.json')))
    g = json.load(open(os.path.join(a.dir, 'context-gain.json')))
    c = json.load(open(os.path.join(a.dir, 'calibration.json')))
    L = ['# 005M bake-off tables (generated by research/analyzer-005m/summarize.py — do not edit by hand)', '']
    L.append('Rates are over every question asked in the matched set; brackets are Wilson 95 % intervals. CONFIDENT_WRONG = a wrong '
             'answer stated with confidence HIGH (primary); P80 = a wrong answer whose own option probability is ≥ 0.80 (005J rule). '
             'UNRESOLVED is never wrong.')
    for tname in ('PHASE1', 'PHASE2'):
        t = b['tables'].get(tname)
        if not t:
            continue
        L += ['', f'## {tname} — {t["questions"]} matched questions × 5 modes', '',
              '| model | mode | exact accuracy | resolved accuracy | coverage | UNRESOLVED | failures | **CONFIDENT_WRONG_RATE** | P80 rate | median wall | image tokens |',
              '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
        for m in t['models']:
            for mode in MODES + ['ALL_MODES']:
                s = t['byModelMode'][f'{m}|{mode}']
                lat = t['latency'].get(f'{m}|{mode}', {})
                tok = t['tokens'].get(f'{m}|{mode}', {})
                L.append(f"| {m} | {SHORT.get(mode, 'all')} | {pct(s['exactAccuracy'])} | {short(s['resolvedAccuracy'])} | {short(s['coverage'])} | {s['unresolved']} | {s['failures']} | "
                         f"**{pct(s['CONFIDENT_WRONG_RATE'])}** | {short(s['CONFIDENT_WRONG_P80_RATE'])} | "
                         f"{(lat.get('medianWallMs') or 0) / 1000:.1f} s | {tok.get('medianImageTokens', '—')} |" if mode != 'ALL_MODES' else
                         f"| {m} | **all** | {pct(s['exactAccuracy'])} | {short(s['resolvedAccuracy'])} | {short(s['coverage'])} | {s['unresolved']} | {s['failures']} | **{pct(s['CONFIDENT_WRONG_RATE'])}** | {short(s['CONFIDENT_WRONG_P80_RATE'])} | | |")
        L += ['', f'### {tname} — real development vs synthetic (exact accuracy / CONFIDENT_WRONG_RATE)', '',
              '| model | mode | REAL_ALL | SYNTH_ALL | ' + ' | '.join(s for s in ['REAL_DEV', 'ROUND8_DEV', 'MURAJACH_DEV', 'STOREY_DEV', 'GAPSET_DEV', 'SYNTH_CF', 'SYNTH_GLOBAL']) + ' |',
              '| --- | --- | --- | --- | ' + ' | '.join('---' for _ in range(7)) + ' |']
        for m in t['models']:
            for mode in MODES:
                bs = t['bySet'][f'{m}|{mode}']
                cell = lambda k: (f"{short(bs[k]['exactAccuracy'])} / {short(bs[k]['CONFIDENT_WRONG_RATE'])}" if k in bs else '—')
                L.append(f"| {m} | {SHORT[mode]} | {cell('REAL_ALL')} | {cell('SYNTH_ALL')} | " + ' | '.join(cell(k) for k in ['REAL_DEV', 'ROUND8_DEV', 'MURAJACH_DEV', 'STOREY_DEV', 'GAPSET_DEV', 'SYNTH_CF', 'SYNTH_GLOBAL']) + ' |')
        L += ['', f'### {tname} — baselines (no model)', '', '| set | n | majority answer | majority accuracy | constant letter "A" |', '| --- | --- | --- | --- | --- |']
        for s, v in t['baselines'].items():
            L.append(f"| {s} | {v['n']} | {v['majorityAnswer']} | {100 * v['majorityAccuracy']:.1f} % | {100 * v['constantLetterA']:.1f} % |")
        L += ['', f'### {tname} — consistency (same semantic answer on matched twins, both answered)', '',
              '| model | mode | mirror | rotation 90° | counterfactual pairs answered | both members right | same answer to both (insensitive) |', '| --- | --- | --- | --- | --- | --- | --- |']
        for m in t['models']:
            for mode in MODES:
                k = t['consistency'][f'{m}|{mode}']
                L.append(f"| {m} | {SHORT[mode]} | {short(k['mirror'])} | {short(k['rotation90'])} | {k['counterfactualPairsAnswered']} | {short(k['counterfactualBothRight'])} | {short(k['counterfactualSameAnswer'])} |")
        L += ['', f'### {tname} — per class, exact accuracy in mode D', '']
        classes = sorted({cl for m in t['models'] for cl in t['byClass'][f'{m}|D_MARKED_ROI_PLUS_CROP']})
        L += ['| class | ' + ' | '.join(t['models']) + ' |', '| --- | ' + ' | '.join('---' for _ in t['models']) + ' |']
        for cl in classes:
            L.append(f'| {cl} | ' + ' | '.join(short(t['byClass'][f'{m}|D_MARKED_ROI_PLUS_CROP'].get(cl, {}).get('exactAccuracy')) for m in t['models']) + ' |')
    if b.get('phase1Ranking'):
        L += ['', '## Phase-1 ranking (pre-registered: CONFIDENT_WRONG_RATE over all five modes, then exact accuracy)', '', '| rank | model | CONFIDENT_WRONG_RATE | exact accuracy |', '| --- | --- | --- | --- |']
        for i, r in enumerate(b['phase1Ranking'], 1):
            L.append(f"| {i} | {r['model']} | {100 * r['cwr']:.1f} % | {100 * r['exactAccuracy']:.1f} % |")
    L += ['', '## Context gain — A_CROP_ONLY against the modes with the whole plan', '',
          '| model | set | A → | WRONG→RIGHT | UNRESOLVED→RIGHT | WRONG→UNRESOLVED | RIGHT→WRONG | OTHER | SAME | net right gain | context-dependent: right in A → right in mode (n) |',
          '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for m, gm in g['byModel'].items():
        for mode in MODES[1:]:
            x = gm.get(f'A->{mode}')
            if not x:
                continue
            tr = x['transitions']
            cd = x['contextDependentOnly']
            L.append(f"| {m} | {gm['set']} | {SHORT[mode]} | {tr.get('WRONG->RIGHT', 0)} | {tr.get('UNRESOLVED->RIGHT', 0)} | {tr.get('WRONG->UNRESOLVED', 0)} | {tr.get('RIGHT->WRONG', 0)} | {tr.get('OTHER', 0)} | {tr.get('SAME', 0)} | {x['netRightGain']:+d} | {cd['rightInA']} → {cd['rightInMode']} ({cd['n']}) |")
    L += ['', '## Calibration (answered items; all five modes pooled)', '',
          '| model | answered | HIGH share | accuracy when HIGH | when MEDIUM | when LOW | ECE (option prob.) | AUROC (option prob.) | unconstrained option mass (median) |', '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for m, cm in c['byModel'].items():
        x = cm['ALL_MODES']
        sc = x['statedConfidence']
        L.append(f"| {m} | {x['answered']} | {short(x['highShare'])} | {short(sc['HIGH'])} | {short(sc['MEDIUM'])} | {short(sc['LOW'])} | {x['ECE']} | {x['AUROC']} | {cm['unconstrainedEnumMass']['median']} |")
    if b.get('oldSmolVLM2_500M'):
        o = b['oldSmolVLM2_500M']
        L += ['', '## The old SmolVLM2-500M (005J) on the exact intersection', '', o['note'], '',
              f"Intersection: {o['intersectionQuestions']} questions. SmolVLM2-500M right on {o['right']}, UNRESOLVED on {o['unresolved']}, confident-wrong (p ≥ 0.80) on {o['confidentWrongP80']}.", '',
              '| model | mode | exact accuracy | CONFIDENT_WRONG_RATE |', '| --- | --- | --- | --- |']
        for k, s in o['newModelsOnIntersection'].items():
            m, mode = k.split('|')
            L.append(f"| {m} | {SHORT[mode]} | {short(s['exactAccuracy'])} | {short(s['CONFIDENT_WRONG_RATE'])} |")
    open(a.out, 'w').write('\n'.join(L) + '\n')
    print(a.out, len(L), 'lines')


if __name__ == '__main__':
    main()
