#!/usr/bin/env python3
"""summarize.py - markdown tables from the scorer's JSON (RESEARCH ONLY). Every number in the 005M report is read here.

    python -I -B research/analyzer-005m/summarize.py --dir stage-reports/artifacts/analyzer-005m-vr2 --out <dir>/bakeoff-tables.md
"""
import argparse
import json
import os

MODES = ['A_CROP_ONLY', 'B_FULL_PLAN', 'C_FULL_PLAN_MARKED_ROI', 'D_MARKED_ROI_PLUS_CROP', 'E_MARKED_ROI_PLUS_CROP_PLUS_OVERLAY']
SHORT = {m: m[0] for m in MODES}
SETS = ['REAL_DEV', 'ROUND8_DEV', 'MURAJACH_DEV', 'STOREY_DEV', 'GAPSET_DEV', 'SYNTH_CF', 'SYNTH_GLOBAL']


def pct(r):
    if not r or r.get('rate') is None:
        return '—'
    lo, hi = r['wilson95']
    return f"{100 * r['rate']:.1f} % ({r['k']}/{r['n']}; {100 * lo:.0f}–{100 * hi:.0f})"


def short(r):
    if not r or r.get('rate') is None:
        return '—'
    return f"{100 * r['rate']:.0f} % ({r['k']}/{r['n']})"


def rng(ci):
    if not ci or ci[0] is None:
        return '—'
    return f'{100 * ci[0]:.0f}–{100 * ci[1]:.0f}'


def sgn(ci):
    if not ci or ci[0] is None:
        return '—'
    return f'{100 * ci[0]:+.1f} … {100 * ci[1]:+.1f}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    b = json.load(open(os.path.join(a.dir, 'matched-bakeoff.json')))
    g = json.load(open(os.path.join(a.dir, 'context-gain.json')))
    c = json.load(open(os.path.join(a.dir, 'calibration.json')))
    L = ['# 005M bake-off tables (generated by research/analyzer-005m/summarize.py — do not edit by hand)', '']
    L.append('**How to read these tables**')
    L += [
        '- Rates are over every question asked in the matched set.',
        '- Brackets are Wilson 95 % intervals, which treat every row as independent. **"cluster 95 %"** resamples whole real '
        'houses and whole synthetic scene pairs, and is the interval to use when comparing.',
        '- **CONFIDENT_WRONG** (the pre-registered primary) is a wrong answer stated with confidence HIGH.',
        '  - These models state HIGH on almost every reply, so CONFIDENT_WRONG_RATE is in effect the wrong-answer rate.',
        '  - **HIGH share** and **p ≥ 0.8 share** show how much of a reply the confidence really separates.',
        '- **P80** is a wrong answer whose own option probability is ≥ 0.80 (005J\'s rule).',
        '- UNRESOLVED is never wrong.',
        f"- **{len(b.get('excluded', {}))} questions are excluded** from every amended table (`excluded-items.json`, post-review B-1, "
        'B-2/D-1). The pre-registered rows over every question follow each table.',
    ]
    for tname in ('PHASE1', 'PHASE2'):
        t = b['tables'].get(tname)
        if not t:
            continue
        cb = t['clusterBootstrap']
        L += ['', f'## {tname} — {t["questions"]} matched questions × 5 modes ({t["clusters"]["n"]} independent clusters)', '',
              '| model | mode | exact accuracy | cluster 95 % | resolved acc. | coverage | UNRESOLVED | fail | **CONFIDENT_WRONG_RATE** | cluster 95 % | HIGH share | p ≥ 0.8 share | P80 rate | median wall | image tokens |',
              '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
        for m in t['models']:
            for mode in MODES + ['ALL_MODES']:
                k = f'{m}|{mode}'
                s = t['byModelMode'][k]
                arm = cb['byArm'][k]
                lat = t['latency'].get(k, {})
                tok = t['tokens'].get(k, {})
                wall = f"{(lat.get('medianWallMs') or 0) / 1000:.1f} s" if mode != 'ALL_MODES' else ''
                L.append(f"| {m} | {'**all**' if mode == 'ALL_MODES' else SHORT[mode]} | {pct(s['exactAccuracy'])} | {rng(arm['exactAccuracy95'])} | {short(s['resolvedAccuracy'])} | "
                         f"{short(s['coverage'])} | {s['unresolved']} | {s['failures']} | **{pct(s['CONFIDENT_WRONG_RATE'])}** | {rng(arm['CONFIDENT_WRONG_RATE95'])} | "
                         f"{short(s['statedHighShareAmongAnswered'])} | {short(s['p80ShareAmongAnswered'])} | {short(s['CONFIDENT_WRONG_P80_RATE'])} | {wall} | {tok.get('medianImageTokens', '') if mode != 'ALL_MODES' else ''} |")
        pre = b.get('preRegistered', {}).get(tname)
        if pre:
            L += ['', f'Pre-registered set (all {b[tname.lower() + "QuestionsPreRegistered"]} questions, nothing excluded), all modes pooled:', '',
                  '| model | exact accuracy | CONFIDENT_WRONG_RATE |', '| --- | --- | --- |']
            for m in t['models']:
                s = pre[f'{m}|ALL_MODES']
                L.append(f"| {m} | {pct(s['exactAccuracy'])} | {pct(s['CONFIDENT_WRONG_RATE'])} |")
        L += ['', f'### {tname} — image-free baselines (no model)', '',
              '| set | n | always A | always B | always C | first-option rule | per-class majority (fitted, upper bound) |', '| --- | --- | --- | --- | --- | --- | --- |']
        for s, v in t['baselines'].items():
            al = v['alwaysLetter']
            L.append(f"| {s} | {v['n']} | {short(al['A'])} | {short(al['B'])} | {short(al['C'])} | {short(v['firstOptionRule'])} | {short(v['perClassMajorityFittedUpperBound'])} |")
        L += ['', f'### {tname} — model minus the first-option rule (exact accuracy, cluster bootstrap)', '',
              '| model | ' + ' | '.join(SHORT[m] for m in MODES) + ' | all |', '| --- | ' + ' | '.join('---' for _ in MODES) + ' | --- |']
        for m in t['models']:
            cells = []
            for mode in MODES + ['ALL_MODES']:
                x = cb['modelMinusFirstOptionPrior'][f'{m}|{mode}']
                cells.append(f"{sgn(x['ci95'])} (P>0 {100 * x['shareAboveZero']:.0f} %)")
            L.append(f'| {m} | ' + ' | '.join(cells) + ' |')
        if cb['pairwise']:
            L += ['', f'### {tname} — model against model (cluster bootstrap, paired; percentage points)', '',
                  '| pair | mode | Δ CONFIDENT_WRONG_RATE 95 % | Δ exact accuracy 95 % |', '| --- | --- | --- | --- |']
            for k, v in cb['pairwise'].items():
                pair, mode = k.split('|')
                if mode in ('ALL_MODES', 'D_MARKED_ROI_PLUS_CROP'):
                    L.append(f"| {pair} | {'all' if mode == 'ALL_MODES' else 'D'} | {sgn(v['cwrDiff95'])} | {sgn(v['accDiff95'])} |")
        L += ['', f'### {tname} — by set and truth source (exact accuracy / CONFIDENT_WRONG_RATE)', '',
              '| model | mode | REAL_ALL | REAL, human truth | REAL, AI-authored truth | SYNTH_ALL | ' + ' | '.join(SETS) + ' |',
              '| --- | --- | --- | --- | --- | --- | ' + ' | '.join('---' for _ in SETS) + ' |']
        for m in t['models']:
            for mode in MODES + ['ALL_MODES']:
                bs = t['bySet'].get(f'{m}|{mode}', {})
                cell = lambda k: (f"{short(bs[k]['exactAccuracy'])} / {short(bs[k]['CONFIDENT_WRONG_RATE'])}" if k in bs else '—')
                L.append(f"| {m} | {'all' if mode == 'ALL_MODES' else SHORT[mode]} | {cell('REAL_ALL')} | {cell('REAL_HUMAN_TRUTH')} | {cell('REAL_AI_AUTHORED_TRUTH')} | {cell('SYNTH_ALL')} | "
                         + ' | '.join(cell(k) for k in SETS) + ' |')
        p = t['pairs']
        L += ['', f'### {tname} — consistency', '',
              f"Pairs: {p['mirror']} mirror, {p['rotation90']} rotation, {p['counterfactualContext']} counterfactual pairs that need the whole plan "
              f"(byte-identical crops), {p['counterfactualLocal']} local counterfactual pairs, {p['counterfactualSameTruthControls']} same-truth control pairs "
              '(left out of the rates).', '',
              '"Same answer" on a counterfactual pair means the model did not see the difference. On context pairs in mode A that '
              'is forced: the crops are identical.', '',
              '| model | mode | mirror (both answered) | mirror (005J denominator) | rotation 90° | context pairs: both right / all pairs | context pairs: same answer | local pairs: both right | local pairs: same answer |',
              '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
        for m in t['models']:
            for mode in MODES:
                k = t['consistency'][f'{m}|{mode}']
                cx, lc = k['counterfactualContextPairs'], k['counterfactualLocalPairs']
                L.append(f"| {m} | {SHORT[mode]} | {short(k['mirror'])} | {short(k['mirror005jDenominator'])} | {short(k['rotation90'])} | {short(cx['bothRightOfAllPairs'])} | "
                         f"{short(cx['sameAnswer'])} | {short(lc['bothRight'])} | {short(lc['sameAnswer'])} |")
        L += ['', f'### {tname} — per class, exact accuracy in mode D', '']
        classes = sorted({cl for m in t['models'] for cl in t['byClass'][f'{m}|D_MARKED_ROI_PLUS_CROP']})
        L += ['| class | ' + ' | '.join(t['models']) + ' |', '| --- | ' + ' | '.join('---' for _ in t['models']) + ' |']
        for cl in classes:
            L.append(f'| {cl} | ' + ' | '.join(short(t['byClass'][f'{m}|D_MARKED_ROI_PLUS_CROP'].get(cl, {}).get('exactAccuracy')) for m in t['models']) + ' |')
    for key, title in (('phase1RankingPreRegistered', 'pre-registered set: the decision that was taken'), ('phase1Ranking', 'amended set')):
        if b.get(key):
            L += ['', f'## Phase-1 ranking, {title} (CONFIDENT_WRONG_RATE over all five modes, then exact accuracy)', '', '| rank | model | CONFIDENT_WRONG_RATE | exact accuracy |', '| --- | --- | --- | --- |']
            for i, r in enumerate(b[key], 1):
                L.append(f"| {i} | {r['model']} | {100 * r['cwr']:.1f} % | {100 * r['exactAccuracy']:.1f} % |")
    for tname, gt in g['tables'].items():
        L += ['', f'## Context gain — {tname}: A_CROP_ONLY against the modes with the whole plan', '',
              '| model | A → | WRONG→RIGHT | UNRESOLVED→RIGHT | WRONG→UNRESOLVED | RIGHT→WRONG | OTHER (breakdown) | SAME | net change in right answers | context-dependent: right in A → right in mode (n) |',
              '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
        for m, gm in gt.items():
            for mode in MODES[1:]:
                x = gm[f'A->{mode}']
                tr = x['transitions']
                cd = x['contextDependentOnly']
                ob = ', '.join(f'{k} {v}' for k, v in x['otherBreakdown'].items())
                L.append(f"| {m} | {SHORT[mode]} | {tr.get('WRONG->RIGHT', 0)} | {tr.get('UNRESOLVED->RIGHT', 0)} | {tr.get('WRONG->UNRESOLVED', 0)} | {tr.get('RIGHT->WRONG', 0)} | "
                         f"{tr.get('OTHER', 0)}{' (' + ob + ')' if ob else ''} | {tr.get('SAME', 0)} | {x['netRightChange']:+d} | {cd['rightInA']} → {cd['rightInMode']} ({cd['n']}) |")
    for tname, ct in c['tables'].items():
        L += ['', f'## Calibration — {tname} (answered items)', '',
              '| model | subset | mode | answered | HIGH share | accuracy when HIGH | ECE | AUROC |', '| --- | --- | --- | --- | --- | --- | --- | --- |']
        for m, cm in ct.items():
            for mode in ('ALL_MODES', 'D_MARKED_ROI_PLUS_CROP'):
                x = cm[mode]
                L.append(f"| {m} | all | {'all' if mode == 'ALL_MODES' else 'D'} | {x['answered']} | {short(x['highShare'])} | {short(x['statedConfidence']['HIGH'])} | {x['ECE']} | {x['AUROC']} |")
                for sub in ('REAL_ALL', 'SYNTH_ALL'):
                    y = cm['bySubset'][sub][mode]
                    L.append(f"| {m} | {sub} | {'all' if mode == 'ALL_MODES' else 'D'} | {y['answered']} | {short(y['highShare'])} | {short(y['statedConfidence']['HIGH'])} | {y['ECE']} | {y['AUROC']} |")
        L += ['', f'### Risk–coverage of the option probability — {tname}', '',
              'This is **in-sample**. Thresholds were fixed in advance, but any operating point read off these rows was chosen on '
              'the answers it is scored on. The "zero-error region" is the coverage above the highest probability that any wrong '
              'answer received.', '',
              '| model | slice | p ≥ 0 | 0.8 | 0.9 | 0.95 | 0.99 | 0.999 | in-sample zero-error region | C+D+E agree: kept, wrong | all five agree: kept, wrong |',
              '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
        for m, cm in ct.items():
            for sl, rcv in cm['riskCoverage'].items():
                cur = {x['threshold']: x for x in rcv['curve']}
                cell = lambda th: (f"cov {100 * cur[th]['coverage']:.0f} %, risk {100 * cur[th]['selectiveRisk']:.0f} % (≤ {100 * cur[th]['wilsonUpper']:.0f})"
                                   if cur[th]['selectiveRisk'] is not None else '—')
                z = rcv['inSampleZeroErrorRegion']
                ag = cm['agreementFilter']
                agc = lambda n: f"{ag[n]['questionsKept']}/{ag[n]['of']}, {short(ag[n]['wrongAmongKept'])}"
                L.append(f"| {m} | {sl.replace('D_MARKED_ROI_PLUS_CROP', 'D')} | {cell(0.0)} | {cell(0.8)} | {cell(0.9)} | {cell(0.95)} | {cell(0.99)} | {cell(0.999)} | "
                         f"p > {z['aboveP']:.4f}: {z['covered']} ({100 * (z['coverage'] or 0):.1f} %) | {agc('C+D+E agree') if sl == 'ALL_MODES' else ''} | {agc('all five agree') if sl == 'ALL_MODES' else ''} |")
    if b.get('oldSmolVLM2_500M'):
        o = b['oldSmolVLM2_500M']
        L += ['', '## The old SmolVLM2-500M (005J) on the exact intersection', '', o['note'], '',
              f"Intersection: {o['intersectionQuestions']} questions. SmolVLM2-500M: right on {o['right']}, UNRESOLVED on "
              f"{o['unresolved']}, P80 confident-wrong on **{o['confidentWrongP80']}**.", '',
              '| model | mode | exact accuracy | **P80 confident-wrong (like for like)** | CONFIDENT_WRONG (stated HIGH; no 005J counterpart) |',
              '| --- | --- | --- | --- | --- |']
        for k, s in o['newModelsOnIntersection'].items():
            m, mode = k.split('|')
            L.append(f"| {m} | {SHORT[mode]} | {short(s['exactAccuracy'])} | **{short(s['CONFIDENT_WRONG_P80_RATE'])}** | {short(s['CONFIDENT_WRONG_RATE'])} |")
    open(a.out, 'w').write('\n'.join(L) + '\n')
    print(a.out, len(L), 'lines')


if __name__ == '__main__':
    main()
