/**
 * The unresolved-evidence ledger: what the source does not settle, what was
 * observed and deliberately not modelled, and the contradictions the earlier
 * research recorded, each carried forward rather than absorbed.
 */
export type LedgerEntry = {
  id: string
  kind: 'UNRESOLVED' | 'NOT_MODELLED' | 'CONTRADICTION' | 'RESOLVED_CONTRADICTION' | 'SIMPLIFICATION'
  what: string
  why: string
  /** How the model handles it. */
  handling: string
}

export const MARCOWKI_LEDGER: readonly LedgerEntry[] = [
  { id: 'eave-datum', kind: 'CONTRADICTION', what: 'The section prints the eave datum +4,67; the printed span 7.90, pitch 40° and ridge +7,95 put the roof plane at 4.63556 at the outer wall face.', why: 'Both are printed on the same drawing; taking +4,67 would make the built pitch 39.71°.', handling: 'The roof uses the derived plane 4.63556 (SOURCE_DERIVED); the printed datum is kept as constraint c-eave-datum and in the roof evidence note.' },
  { id: 'house-garage-wall', kind: 'RESOLVED_CONTRADICTION', what: 'The reference research modelled the house/garage partition as two abutting 0.45 m walls (0.90 m) and recorded it as unresolved.', why: 'Its ring compiler had no shared-wall or T-junction semantics. The drawings show one 0.45 m wall, and the garage interior 7.90..11.60 (published 24.10 m²) only closes with a single leaf.', handling: 'One wall (g-right) hosts the garage: gar-rear T-junctions into it and gar-front continues its line. The kotłownia door is therefore a single-leaf opening; the two-leaf reading is not source-supported.' },
  { id: 'upper-slab-footprint', kind: 'RESOLVED_CONTRADICTION', what: 'The shell gold insets the upper slab to the bearing rectangle x 0.45..7.45; the interior gold spans the whole 7.90 × 12.60 outline.', why: 'Both mean the one plate at +3,06; the section gives the 0.45 m zone to the wall.', handling: 'The bearing rectangle, notched by the stair void, as the roof-features gold reconciled it. How far the plate bears into the wall stays unresolved.' },
  { id: 'balcony-thickness', kind: 'UNRESOLVED', what: 'The balcony slabs’ thickness (0.55) and top (2.96).', why: 'Read off the rear elevation fascia 2.41..2.96; the plans dimension neither.', handling: 'Modelled as measured, VISUAL_INFERRED on the properties.' },
  { id: 'railing-height', kind: 'UNRESOLVED', what: 'The glass balustrade height 0.90.', why: 'The elevations put the glass top 0.89..0.93 m above the measured slab top, below a normal balustrade; either the slab top is lower or the renders omit a top rail.', handling: 'Modelled at 0.90, VISUAL_INFERRED.' },
  { id: 'railing-posts', kind: 'SIMPLIFICATION', what: 'Balustrade posts stand at the plan marks (four equal panels front, four ~1.5 m panels rear).', why: 'BuildApp railings space posts equally over a run.', handling: 'The measured run and panel count are kept (post spacing 0.93 / 1.62 gives four panels); post positions differ from the plan marks by up to 0.04 m.' },
  { id: 'garage-roof-level', kind: 'UNRESOLVED', what: 'The garage flat roof level: section 2.88 against elevation band tops 2.99..3.14.', why: 'A ~0.2 m parapet upstand the section does not draw.', handling: 'Roof at 2.88; the portal head at the measured 3.08; the parapet is not modelled.' },
  { id: 'kotlownia-door-head', kind: 'UNRESOLVED', what: 'The kotłownia/garage door head height.', why: 'No drawing dimensions it.', handling: '2.10 assumed, matching every other single door (ASSUMED on height).' },
  { id: 'balcony-west-edge', kind: 'CONTRADICTION', what: 'The front balcony west edge: attic plan 3.338, front elevation dark band 3.185..3.236.', why: 'Plan and render disagree by 0.15 m.', handling: 'The plan is taken per the authority order; the difference is left standing.' },
  { id: 'gable-head-clearance', kind: 'UNRESOLVED', what: 'The front gable glazing head: the callout 270/320 leaves 1.68 m of cladding above it; the elevation render suggests ≈1.3 m.', why: 'The dimensioned callout outranks the render.', handling: 'Callout used; the render reading is in the opening’s evidence note.' },
  { id: 'attic-140-220', kind: 'UNRESOLVED', what: 'The printed 140 | 220 pair at the head of the attic plan’s top dimension row.', why: 'Their extension lines fall at x 0.57 and 1.55 and match no drawn feature.', handling: 'No feature depends on them.' },
  { id: 'verge', kind: 'UNRESOLVED', what: 'A verge projection at the gable ends.', why: 'Not dimensioned; the attic plan band above the rear wall is exactly the 100 cm zone.', handling: 'Overhang 0.' },
  { id: 'attic-ceiling', kind: 'SIMPLIFICATION', what: 'Attic partitions are capped at 2.60 m above the attic floor where the roof is higher.', why: 'The plans dimension the knee wall and the ridge, not the ceiling line.', handling: 'ASSUMED on the partitions’ height; below the cap they follow the roof underside.' },
  { id: 'interior-door-heads', kind: 'SIMPLIFICATION', what: 'Interior door heads at 2.00 m.', why: 'No interior opening is dimensioned vertically.', handling: 'ASSUMED on each interior door’s height.' },
  { id: 'stair', kind: 'SIMPLIFICATION', what: 'The stair is a placeholder footprint, not flights; the drawn winders are not represented.', why: 'BuildApp’s stair vocabulary is a placeholder in this stage.', handling: 'The shaft and the slab void are exact; the flights are a later capability.' },
  { id: 'rooflight-cut', kind: 'SIMPLIFICATION', what: 'Rooflight holes are vertical prisms over the unit’s plan rectangle (0.78 along the ridge × 1.18·cos 40° across); the unit sits with vertical sides in the cut.', why: 'A real unit sits perpendicular to the slope; no source dimensions the clearance.', handling: 'Cut = unit, clearance zero (ASSUMED); the plan position and the printed 78/118 are exact.' },
  { id: 'chimney-shafts', kind: 'NOT_MODELLED', what: 'Chimney shafts below the attic floor, the caps, flashings, and the kotłownia flue route (the ground-plan four-flue block sits 1.2 m east of the attic stack).', why: 'Not dimensioned, or would cut the interior walls and the slab.', handling: 'Stacks stand on the attic floor and end at the VISUAL 7.88; both cut the roof.' },
  { id: 'material-bands', kind: 'NOT_MODELLED', what: 'The flush cladding bands (timber on the front gable and rear ground wall, dark render on the west ground storey).', why: 'Materials, not geometry; BuildApp assigns one material per object.', handling: 'The dark render is assigned to the ground front wall and the portal head as VISUAL_INFERRED materials; the bands themselves are recorded here.' },
  { id: 'entrance-sidelight', kind: 'NOT_MODELLED', what: 'The entrance door’s narrow glazed sidelight and mullion; the garage door’s panels; the glazed leaf of the garage side door.', why: 'BuildApp doors are one leaf with a frame, a handle and a hinge.', handling: 'Each is a real cut of the printed size filled with one leaf.' },
  { id: 'terrace-canopy', kind: 'NOT_MODELLED', what: 'The rear terrace paving, the entrance steps, the driveway and the portal soffit lighting strip.', why: 'Outside the building; presentation.', handling: 'The ground slab covers the walled L only; the characteristic zones have no floor slab.' },
  { id: 'footprint-area', kind: 'CONTRADICTION', what: 'Published footprint 131.16 m² against the transcribed L 130.665 m².', why: '0.38 %; the published figure may include the plinth or a projection.', handling: 'Recorded; the chains are used.' },
  { id: 'side-elevation-labels', kind: 'CONTRADICTION', what: 'The published side elevations are labelled LEFT and RIGHT without saying which compass side each is.', why: 'The labels are unreliable.', handling: 'Identified by content: the one with the garage on its left and the 300/230 window is the east view.' },
  { id: 'room-polygon-south', kind: 'UNRESOLVED', what: 'The attic plan draws a recess at the south Pokój’s north-west corner (0.77 m²) and the kotłownia stack stands inside the room polygon.', why: 'The reference kept the printed 398 × 325 rectangle.', handling: 'Polygon as printed; the stack is a separate object standing in it.' },
  { id: 'ground-slab', kind: 'SIMPLIFICATION', what: 'The ground slab is 0.32 m thick.', why: 'The slab build-up is not drawn; 0.32 is the plinth to the −0,32 terrain datum.', handling: 'GEOMETRIC_INFERRED on the thickness.' },
]
