/**
 * The unresolved-evidence ledger: what the source does not settle, what was
 * observed and deliberately not modelled, and the contradictions the earlier
 * research recorded, each carried forward rather than absorbed.
 */
export type LedgerEntry = {
  id: string
  kind: 'UNRESOLVED' | 'NOT_MODELLED' | 'CONTRADICTION' | 'RESOLVED_CONTRADICTION' | 'SIMPLIFICATION'
  what: string
  why: string
  /** How the model handles it. */
  handling: string
}

export const MARCOWKI_LEDGER: readonly LedgerEntry[] = [
  { id: 'eave-datum', kind: 'CONTRADICTION', what: 'The section prints the eave datum +4,67; the printed span 7.90, pitch 40° and ridge +7,95 put the roof plane at 4.63556 at the outer wall face.', why: 'Both are printed on the same drawing; taking +4,67 would make the built pitch 39.71°.', handling: 'The roof uses the derived plane 4.63556 (SOURCE_DERIVED); the printed datum is kept as constraint c-eave-datum and in the roof evidence note.' },
  { id: 'house-garage-wall', kind: 'RESOLVED_CONTRADICTION', what: 'The reference research modelled the house/garage partition as two abutting 0.45 m walls (0.90 m) and recorded it as unresolved.', why: 'Its ring compiler had no shared-wall or T-junction semantics. The drawings show one 0.45 m wall, and the garage interior 7.90..11.60 (published 24.10 m²) only closes with a single leaf.', handling: 'One wall (g-right) hosts the garage: gar-rear T-junctions into it and gar-front continues its line. The kotłownia door is therefore a single-leaf opening; the two-leaf reading is not source-supported.' },
  { id: 'upper-slab-footprint', kind: 'RESOLVED_CONTRADICTION', what: 'The shell gold insets the upper slab to the bearing rectangle x 0.45..7.45; the interior gold spans the whole 7.90 × 12.60 outline.', why: 'Both mean the one plate at +3,06; the section gives the 0.45 m zone to the wall.', handling: 'The bearing rectangle, notched by the stair void, as the roof-features gold reconciled it. How far the plate bears into the wall stays unresolved.' },
  { id: 'balcony-thickness', kind: 'UNRESOLVED', what: 'The balcony slabs’ thickness (0.55) and top (2.96).', why: 'Read off the rear elevation fascia 2.41..2.96; the plans dimension neither.', handling: 'Modelled as measured, VISUAL_INFERRED on the properties.' },
  { id: 'railing-height', kind: 'UNRESOLVED', what: 'The glass balustrade height 0.90.', why: 'The elevations put the glass top 0.89..0.93 m above the measured slab top, below a normal balustrade; either the slab top is lower or the renders omit a top rail.', handling: 'Modelled at 0.90, VISUAL_INFERRED.' },
  { id: 'railing-posts', kind: 'SIMPLIFICATION', what: 'Balustrade posts stand at the plan marks (four equal panels front, four ~1.5 m panels rear).', why: 'BuildApp railings space posts equally over a run.', handling: 'The measured run and panel count are kept (post spacing 0.93 / 1.62 gives four panels); post positions differ from the plan marks by up to 0.04 m.' },
  { id: 'garage-roof-level', kind: 'UNRESOLVED', what: 'The garage flat roof level: section 2.88 against elevation band tops 2.99..3.14.', why: 'A ~0.2 m parapet upstand the section does not draw.', handling: 'Roof at 2.88; the portal head at the measured 3.08; the parapet is not modelled.' },
  { id: 'kotlownia-door-head', kind: 'UNRESOLVED', what: 'The kotłownia/garage door head height.', why: 'No drawing dimensions it.', handling: '2.10 assumed, matching every other single door (ASSUMED on height).' },
  { id: 'balcony-west-edge', kind: 'CONTRADICTION', what: 'The front balcony west edge: attic plan 3.338, front elevation dark band 3.185..3.236.', why: 'Plan and render disagree by 0.15 m.', handling: 'The plan is taken per the authority order; the difference is left standing.' },
  { id: 'gable-head-clearance', kind: 'UNRESOLVED', what: 'The front gable glazing head: the callout 270/320 leaves 1.68 m of cladding above it; the elevation render suggests ≈1.3 m.', why: 'The dimensioned callout outranks the render.', handling: 'Callout used; the render reading is in the opening’s evidence note.' },
  { id: 'attic-140-220', kind: 'UNRESOLVED', what: 'The printed 140 | 220 pair at the head of the attic plan’s top dimension row.', why: 'Their extension lines fall at x 0.57 and 1.55 and match no drawn feature.', handling: 'No feature depends on them.' },
  { id: 'verge', kind: 'UNRESOLVED', what: 'A verge projection at the gable ends.', why: 'Not dimensioned; the attic plan band above the rear wall is exactly the 100 cm zone.', handling: 'Overhang 0.' },
  { id: 'attic-ceiling', kind: 'SIMPLIFICATION', what: 'Attic partitions are capped at 2.60 m above the attic floor where the roof is higher.', why: 'The plans dimension the knee wall and the ridge, not the ceiling line.', handling: 'ASSUMED on the partitions’ height; below the cap they follow the roof underside.' },
  { id: 'interior-door-heads', kind: 'SIMPLIFICATION', what: 'Interior door heads at 2.00 m.', why: 'No interior opening is dimensioned vertically.', handling: 'ASSUMED on each interior door’s height.' },
  { id: 'stair-void-shape', kind: 'RESOLVED_CONTRADICTION', what: 'The interior gold and the BUILDAPP-01 model took the stair void as the 2.08 × 1.98 rectangle x 5.37..7.45 × reference z 6.79..8.77; both plans draw the northern flight past z 6.79 up to its arrival at z 5.66.', why: 'The rectangle was the gold’s simplification of a placeholder stair; the nosing lines on the ground plan and the attic plan’s walking line put the arrival at reference z 5.66.', handling: 'The void is the L the stair occupies (4.158 m²): the southern band z 7.78..8.77 from x 5.37 to the east inner face and the eastern band x 6.46..7.45 north to z 5.66, a hole in the bearing plate that touches the east inner face (schema 1.3.0 `Slab.holes`).' },
  { id: 'stair-winder-count', kind: 'UNRESOLVED', what: 'The number of winders in the stair’s corner: the plans draw thirteen straight risers and no fan lines in the 0.99 × 0.99 corner.', why: 'The rise is the printed 3.06; 13 straight risers plus n winders give a riser of 3.06 / (13 + n).', handling: 'Four winders (0.18 m risers, the value the interior gold assumed) are modelled and marked GEOMETRIC_INFERRED with the alternatives 3 (0.191) and 5 (0.170) recorded in the fact stair.winderRisers; the goings of the straight flights are SOURCE_DERIVED from the nosing lines.' },
  { id: 'stair-waist', kind: 'SIMPLIFICATION', what: 'The stair’s waist (the solid below each nosing) is 0.18 m.', why: 'No drawing shows the stair soffit.', handling: 'ASSUMED on the stair’s waist; the treads, risers and the arrival are measured.' },
  { id: 'rooflight-clearance', kind: 'SIMPLIFICATION', what: 'Rooflight holes are cut normal to the roof plane over the unit’s plan rectangle (0.78 along the ridge × 1.18·cos 40° across) with no clearance around the unit.', why: 'A roof window sits perpendicular to its slope, so the cut is normal (schema 1.3.0 `RoofOpening.cut`); no source dimensions the clearance.', handling: 'Cut mode NORMAL_TO_ROOF (GEOMETRIC_INFERRED: the physics, not a printed figure); clearance zero (ASSUMED); the plan position and the printed 78/118 are exact. The underside outline sits 0.136 m uphill of the top one.' },
  { id: 'chimney-shafts', kind: 'NOT_MODELLED', what: 'Chimney shafts below the attic floor, the caps, flashings, and the kotłownia flue route (the ground-plan four-flue block sits 1.2 m east of the attic stack).', why: 'Not dimensioned, or would cut the interior walls and the slab.', handling: 'Stacks stand on the attic floor and end at the VISUAL 7.88; both cut the roof.' },
  { id: 'finish-regions', kind: 'SIMPLIFICATION', what: 'The flush cladding bands are surface regions on the wall faces (schema 1.3.0): timber on the recessed front wall and up the front gable to the glazing, timber either side of the rear glazing under the balcony, dark render on the west and east ground storeys; the garage and the rear gable read dark render as whole walls.', why: 'Every band edge is read off a render (VISUAL_INFERRED, about ±0.05 m); a band has no thickness in the drawings.', handling: 'Regions carry no thickness and change no wall volume; each edge cites its elevation reading. The front gable band is taken to the glazing jamb 3.94 (the render reads 3.927); the rear band top to the balcony soffit 2.41 (the render reads 2.26 with 0.15 m of shadow under the fascia); the east band ends at the living window jamb (reading 3.906, printed edge 3.896).' },
  { id: 'verge-band', kind: 'NOT_MODELLED', what: 'The white band along the gable rakes on the front and rear elevations (about 0.9 m wide along the slope: the verge fascia and the roof edge seen in elevation).', why: 'A roof edge detail with no dimension; the overhang is 0 (ledger verge).', handling: 'Not modelled; the facade comparison expects the timber gable band to run to the roof soffit where the render shows this band over it.' },
  { id: 'entrance-panel-widths', kind: 'UNRESOLVED', what: 'The split of the 105 entrance opening between the leaf and the glazed sidelight.', why: 'The facade gold reads the leaf over 0..0.72 of the width and the glass over 0.76..1.00; the 1280 px render reads the glass at 0.645..0.95; a render, not a dimension.', handling: 'Assembly LEAF 0.72 | mullion 0.04 | GLAZED 0.28 (VISUAL_INFERRED, ±0.07 of the width); the hinge at the west jamb is ASSUMED.' },
  { id: 'garage-door-panels', kind: 'SIMPLIFICATION', what: 'The garage door is one flush PANEL in the 275/225 reveal.', why: 'The front elevation reads one dark panel with no visible joints; the hero render shows the door rolled up.', handling: 'Assembly PANEL 1 (VISUAL_INFERRED); sectional panel heights are not modelled.' },
  { id: 'terrace-floors', kind: 'SIMPLIFICATION', what: 'The loggia and portal floors are TERRACE plates from ±0,00 down to the −0,32 terrain datum over the two recesses (x 0.61..7.29 rear, 0.61..11.44 front).', why: 'The elevations draw the plinth line continuous under the returns and across both recesses; the section does not cut the recesses.', handling: 'GEOMETRIC_INFERRED on the thickness; the garden paving, the entrance step, the driveway and the portal soffit lighting strip beyond the outer planes are not modelled.' },
  { id: 'footprint-area', kind: 'CONTRADICTION', what: 'Published footprint 131.16 m² against the transcribed L 130.665 m².', why: '0.38 %; the published figure may include the plinth or a projection.', handling: 'Recorded; the chains are used.' },
  { id: 'side-elevation-labels', kind: 'CONTRADICTION', what: 'The published side elevations are labelled LEFT and RIGHT without saying which compass side each is.', why: 'The labels are unreliable.', handling: 'Identified by content: the one with the garage on its left and the 300/230 window is the east view.' },
  { id: 'room-polygon-south', kind: 'UNRESOLVED', what: 'The attic plan draws a recess at the south Pokój’s north-west corner (0.77 m²) and the kotłownia stack stands inside the room polygon.', why: 'The reference kept the printed 398 × 325 rectangle.', handling: 'Polygon as printed; the stack is a separate object standing in it.' },
  { id: 'ground-slab', kind: 'SIMPLIFICATION', what: 'The ground slab is 0.32 m thick.', why: 'The slab build-up is not drawn; 0.32 is the plinth to the −0,32 terrain datum.', handling: 'GEOMETRIC_INFERRED on the thickness.' },
  { id: 'revision-drift', kind: 'CONTRADICTION', what: 'ARCHON’s public sources for the project disagree: the current page (fetched 2026-09-15) prints house 129.04 m², garage 24.10, stairs 5.63, roof 150.57; the older downloadable project card printed 129.15, 23.85, 5.62, 168.48.', why: 'Two revisions of the same published aggregates; the older card is quoted by the stage brief and is not retrievable without a request form.', handling: 'The current page is the reference for published aggregates (docs/MARCOWKI_SOURCE_REVISION_POLICY.md); no aggregate moves a dimension; every geometric figure comes from the dimensioned drawings, which both revisions share.' },
  { id: 'schody-area', kind: 'CONTRADICTION', what: 'The published Schody (stairs) 5.63 m² matches neither the L void (4.158 m²) nor the attic stair compartment as drawn (2.29 × 3.63 = 8.31 m² gross).', why: 'The page measures its rooms to finished surfaces by its own rule and counts the stair by a projection the drawings do not show.', handling: 'Recorded; the void and the compartment come from the plans and the figure moves nothing.' },
  { id: 'garage-door-position', kind: 'CONTRADICTION', what: 'The garage door reveal: the front elevation reads x 8.460..11.274, the ground plan’s measured gap is 8.554..11.308 (printed 275).', why: 'Plan and render disagree by 0.10 m, as they do at the balcony’s west edge.', handling: 'The plan is taken per the authority order; the facade audit records the 0.096 m deviation.' },
  { id: 'verge-white-band', kind: 'CONTRADICTION', what: 'The white face of each return reads 0.10..0.17 m higher on the renders than the return’s top under the roof soffit (4.783 / 4.749 / 4.715 against 4.612 / 4.612 / 4.612 at x 0.30 / 0.30 / 7.60).', why: 'The render’s white includes the roof edge band above the soffit (ledger verge-band); the returns die into the soffit in the model.', handling: 'Recorded as deviations in the facade audit; the returns’ tops are the roof underside, the geometry the section supports.' },
  { id: 'east-band', kind: 'UNRESOLVED', what: 'The east dark band’s north end: the elevation reads dark to reference z 3.906, the printed living window edge is at 3.896.', why: '0.01 m, within the reading’s tolerance.', handling: 'The band ends at the window jamb (wall-local a 8.704).' },
]
